In [71]:
import numpy as np
a = np.zeros((20, 20))
# for i in range (100):
#     for j in range (100):
print (a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [74]:
import random
i = 1
j = 1
count = 0
a = np.zeros((10, 10))
while count < 10:
    i = i + random.randint(0,1)
    j = j + random.randint(0,1)
    count += 1
    a[int(i),int(j)] = count
    if i > 1 and j > 1:
        i = i - random.randint(0,1)
        j = j - random.randint(0,1)
        count += 1
        a[int(i),int(j)] = count
#     print (a[int(i),int(j)])
print (a)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  3.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  5.  4.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  7.  6.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. 11.  8.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. 10.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [69]:
count = 10
for i in range(10):
    for j in range (10):
        i = i + random.randint(0,1)
        j = j + random.randint(0,1)
        count += 1
        

In [70]:
print (count)

110


In [77]:
#---------

In [80]:
walk = [(0,0),(1,0),(1,1),(0,1),(1,-1)]
len (walk)
walk.append(walk[-1])


In [82]:
walk[-1]

(1, -1)

In [86]:
x, y = walk[-1]
my_new = (x+1, y +0)
walk.append(my_new)

In [88]:
walk

[(0, 0), (1, 0), (1, 1), (0, 1), (1, -1), (1, -1), (2, -1), (3, -1), (4, -1)]

In [ ]:
for step in [(1,0),(-1,0),(0,1),(0,-1)]:
    generate_walk (walk,step)